theme = "penguin"

[editor]
line-number = "relative"
scrolloff = 999
popup-border = "all"
auto-format = false
end-of-line-diagnostics = "disable"
completion-timeout = 1
preview-completion-insert = false

[editor.lsp]
display-messages = true
display-inlay-hints = true

[editor.inline-diagnostics]
cursor-line = "warning"

[editor.statusline]
left = ["mode"]
center = []
right = []
mode.normal = "🐧 N"
mode.insert = "🐧 I"
mode.select = "🐧 S"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[keys.normal]
C-s = [":fmt", ":write"]      # format save
C-A-s = "save_selection"
space = { q = { q = ":qa" } }

[keys.insert.j]
k = "normal_mode"
