[colors.bright]
black = "#545454"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#8ae234"
magenta = "#b294bb"
red = "#fc5454"
white = "#ffffff"
yellow = "#fce94f"

[colors.normal]
black = "#3f3f3f"
blue = "#94bff3"
cyan = "#06989a"
green = "#4e9a06"
magenta = "#85678f"
red = "#cc0000"
white = "#dcdccc"
yellow = "#c4a000"

[colors.primary]
background = "#222222"
foreground = "#F9F9F9"

[font]
size = 15.5

[font.normal]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
# family = "BigBlueTerm437 Nerd Font"
# family = "Perfect DOS VGA 437"
# family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.bold]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
style = "Bold"

[font.italic]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
style = "Italic"

[font.bold_italic]
# family = "FiraCode Nerd Font"
family = "Terminess Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[scrolling]
history = 50000

[window]
opacity = 0.95

# [cursor]
# blink_interval= 500
#
# [cursor.style]
# shape = "Beam"
# blinking =  "Always"
#
# [cursor.vi_mode_style]
# shape = "Block"
# blinking = "Off"
