# [terminal.shell]
# program = "/usr/bin/fish"
# args = ["-l"]
[general]
import = [
  "./theme/moonfly.toml",
]

# [colors.bright]
# black = "#545454"
# blue = "#7ec4ff"
# cyan = "#93e0e3"
# green = "#8ae234"
# magenta = "#b294bb"
# red = "#fc5454"
# white = "#ffffff"
# yellow = "#fce94f"
#
# [colors.normal]
# black = "#3f3f3f"
# blue = "#5fb7fe"
# cyan = "#06989a"
# green = "#4e9a06"
# magenta = "#85678f"
# red = "#cc0000"
# white = "#dcdccc"
# yellow = "#c4a000"
#
# [colors.primary]
# background = "#222222"
# foreground = "#F9F9F9"

[font]
size = 16.5

[font.normal]
# family = "FiraCode Nerd Font"
#family = "Terminess Nerd Font"
family = "MonaspiceKr Nerd Font Mono"
# family = "NeoSpleen Nerd Font"
# family = "MonaspaceKrypton"
# family = "BigBlueTerm437 Nerd Font"
# family = "Perfect DOS VGA 437"
# family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.bold]
# family = "FiraCode Nerd Font"
# family = "Terminess Nerd Font"
family = "MonaspiceKr Nerd Font"
style = "SemiBold"

[font.italic]
# family = "FiraCode Nerd Font"
# family = "Terminess Nerd Font"
family = "MonaspiceKr Nerd Font"
style = "Italic"

[font.bold_italic]
# family = "FiraCode Nerd Font"
# family = "Terminess Nerd Font"
family = "MonaspiceKr Nerd Font"
style = "Bold Italic"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

# reference [https://stackoverflow.com/questions/16359878/how-to-map-shift-enter]
[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[scrolling]
history = 50000

[window]
decorations = 'None'
#padding = { x = 3, y = 3 }
opacity = 0.85

[terminal]

# [cursor]
# blink_interval= 500
#
# [cursor.style]
# shape = "Beam"
# blinking =  "Always"
#
# [cursor.vi_mode_style]
# shape = "Block"
# blinking = "Off"
