#! /usr/bin/bash

easifem lint $1 -q >/tmp/temp_lint
grep "^Error:\|^Warning:" -B 4 /tmp/temp_lint | awk 'ORS=NR%5?FS:RS' | tr -s " "

if [[ $(tail /tmp/temp_lint -n 3 | grep -c "exit status 1") -gt 1 ]]; then
	exit 1
else
	exit 0
fi
