# place this file in /etc/keyd and sudo keyd reload
# you can monitor your key events with sudo keyd monitor 
[ids]

0001:0001

[main]

space = overloadt2(layer_one, space, 300)
capslock = layer(control)

# copilot key
f23+leftshift+leftmeta = overload(layer_two, rightmouse)

; = -
' = :

rightalt = overloadt2(shift, space, 300)
katakanahiragana = layer(control)
muhenkan = overloadt2(shift, space, 300)
henkan = overloadt2(alt, space, 300)
yen = +
ro = \  
[ = @
] = [
\ = ]

[layer_one]
h = left
j = down
k = up
l = right

a = +
s = "
e = esc
d = $
i = !
t = ~
r = ^
m = *
u = _
p = %

henkan = backspace
muhenkan = space
capslock = layer(meta)

; = ;
' = = 

[shift]
1 = ! 
2 = "
3 = # 
4 = $ 
5 = %
6 = & 
7 = '
8 = (
9 = ) 
0 = ~ 

henkan = backspace

[layer_two]
1 = macro(s h i m i z u . s h i o n 8 1 9 @ g m a i l . c o m )
2 = macro(s h i m i z u . s h i o n . 2 3 z @ s t . k y o t o - u . a c . j p )
3 = macro(p g n - e m p e r o r 5 3 1 @ i . s o f t b a n k . j p ) 

capslock = `

