# function template generated by "fpt"
function easifem-fish-utility -d "easifem fish utility"
    argparse \
        -x 'v,h' \
        v/version h/help -- $argv
    or return 1

    set --local version_easifem_fish_utility 'v0.0.1'

    if set -q _flag_version
        echo "easifem-fish-utility: " $version_easifem_fish_utility
    else if set -q _flag_help
        __easifem-fish-utility_help
    else
        # main body
    end
end

# helper function
function __easifem-fish-utility_help
    printf '%s\n' \
        'USAGE:' \
        '      easifem-fish-utility [OPTION]' \
        'OPTIONS:' \
        '      -v, --version       Show version info' \
        '      -h, --help          Show help'
end
